### ISSUE TITLE
Disable admin menu hider

### ISSUE THREAD

**Issue by aitala** [psudug/nittany#2]
Disable admin menu hider - very confusing on startup as menu is not visible, but is space for it is.

**Comment by aitala** [comment]
Also there are no docs or help for the module - may want to submit patch to author?

**Comment by btopro** [comment]
nope, it's a requirement on every system ever, we can make it show by default but hit ` and you'll be happy

**Comment by btopro** [comment]
on but checkbox set so that it shows up by default. ` will hide it, great for showing things
